project "magma"
  kind "StaticLib"
  language "C++"
  location ""
  cppdialect "C++20"
  floatingpoint "Strict"

  glslc="%VULKAN_SDK%/Bin/glslangValidator"
  GLSL_DIR= "src/auxiliary/spirv"
  SPIRV_DIR= GLSL_DIR .. "/output"

  includedirs {
    "src",
    "src/allocator",
    "src/auxillary",
    "src/barriers",
    "src/core",
    "src/descriptors",
    "src/exceptions",
    "src/extensions",
    "src/helpers",
    "src/misc",
    "src/objects",
    "src/packed",
    "src/platform",
    "src/raytracing",
    "src/renderpass",
    "src/shaders",
    "src/states",
    "src/third-party/SPIRV-Reflect/include",
    "src/third-party/SPIRV-Reflect/VulkanMemoryAllocator/include",

    "%VULKAN_SDK%/Include"
  }

  -- common files
  files {
    "src/magma.cpp",
    "src/allocator/alignedAllocator.cpp",
    "src/allocator/allocationCallbacks.cpp",
    -- "src/allocator/cxxAllocator.cpp",
    "src/allocator/debugAlignedAllocator.cpp",
    "src/allocator/deviceMemoryAllocator.cpp",
    "src/auxiliary/accumulationBuffer.cpp",
    "src/auxiliary/auxframebuffer.cpp",
    "src/auxiliary/blitRectangle.cpp",
    "src/auxiliary/fillRectangleVertexShader.cpp",
    "src/auxiliary/frameGrabber.cpp",
    "src/auxiliary/generateMipmap.cpp",
    "src/auxiliary/graphicsPipelineCache.cpp",
    "src/auxiliary/imageDescriptorSet.cpp",
    "src/auxiliary/immediateRender.cpp",
    "src/auxiliary/profiler.cpp",
    "src/auxiliary/shaderCompiler.cpp",
    "src/auxiliary/sprite.cpp",
    "src/auxiliary/textShader.cpp",
    "src/barriers/imageMemoryBarrier.cpp",
    "src/descriptors/accelerationStructureDescriptor.cpp",
    "src/descriptors/bufferDescriptor.cpp",
    "src/descriptors/imageDescriptor.cpp",
    "src/exceptions/errorResult.cpp",
    "src/exceptions/exception.cpp",
    "src/exceptions/reflectionErrorResult.cpp",
    "src/extensions/deviceExtensions.cpp",
    "src/extensions/instanceExtensions.cpp",
    "src/extensions/instanceLayers.cpp",
    "src/helpers/executeCommandBuffer.cpp",
    "src/helpers/executeDeferredOperation.cpp",
    "src/helpers/layoutTransition.cpp",
    "src/helpers/streamInsertOperators.cpp",
    "src/helpers/stringifyFlags.cpp",
    "src/misc/application.cpp",
    "src/misc/deviceFaultInfo.cpp",
    "src/misc/deviceFeatures.cpp",
    "src/misc/deviceQueueDescriptor.cpp",
    "src/misc/featureQuery.cpp",
    "src/misc/finish.cpp",
    "src/misc/format.cpp",
    "src/misc/framebufferAttachmentImage.cpp",
    "src/misc/pipelineExecutable.cpp",
    "src/misc/scopedDebugMarker.cpp",
    "src/misc/sharing.cpp",
    "src/misc/structureChain.cpp",
    "src/objects/model/deviceChild.cpp",
    "src/objects/accelerationStructure.cpp",
    "src/objects/accelerationStructureInputBuffer.cpp",
    "src/objects/baseDeviceMemory.cpp",
    "src/objects/baseUniformBuffer.cpp",
    "src/objects/bottomLevelStructure.cpp",
    "src/objects/buffer.cpp",
    "src/objects/bufferView.cpp",
    "src/objects/commandBuffer.cpp",
    "src/objects/commandBufferDebug.cpp",
    "src/objects/commandPool.cpp",
    "src/objects/computePipeline.cpp",
    "src/objects/computePipelineBatch.cpp",
    "src/objects/computePipelineLibrary.cpp",
    "src/objects/conditionalRenderingBuffer.cpp",
    "src/objects/countBuffer.cpp",
    "src/objects/debugReportCallback.cpp",
    "src/objects/debugUtilsMessenger.cpp",
    "src/objects/deferredOperation.cpp",
    "src/objects/descriptorPool.cpp",
    "src/objects/descriptorSet.cpp",
    "src/objects/descriptorSetLayout.cpp",
    "src/objects/device.cpp",
    "src/objects/deviceMemory.cpp",
    "src/objects/deviceResourcePool.cpp",
    "src/objects/display.cpp",
    "src/objects/displayMode.cpp",
    "src/objects/dstTransferBuffer.cpp",
    "src/objects/dynamicUniformBuffer.cpp",
    "src/objects/event.cpp",
    "src/objects/externalImage.cpp",
    "src/objects/fence.cpp",
    "src/objects/fragmentDensityMap.cpp",
    "src/objects/fragmentDensityMapView.cpp",
    "src/objects/fragmentShadingRateAttachment.cpp",
    "src/objects/framebuffer.cpp",
    "src/objects/fullScreenExclusiveSwapchain.cpp",
    "src/objects/graphicsPipeline.cpp",
    "src/objects/graphicsPipelineBatch.cpp",
    "src/objects/graphicsPipelineLibrary.cpp",
    "src/objects/image.cpp",
    "src/objects/image1D.cpp",
    "src/objects/image1DArray.cpp",
    "src/objects/image2D.cpp",
    "src/objects/image2DArray.cpp",
    "src/objects/image3D.cpp",
    "src/objects/imageAttachment.cpp",
    "src/objects/imageCube.cpp",
    "src/objects/imagelessFramebuffer.cpp",
    "src/objects/imageView.cpp",
    "src/objects/indexBuffer.cpp",
    "src/objects/indirectBuffer.cpp",
    "src/objects/instance.cpp",
    "src/objects/leanCommandBuffer.cpp",
    "src/objects/managedDeviceMemory.cpp",
    "src/objects/multiviewRenderPass.cpp",
    "src/objects/mutableImage.cpp",
    "src/objects/mutableImageView.cpp",
    "src/objects/physicalDevice.cpp",
    "src/objects/physicalDeviceFeatures.cpp",
    "src/objects/physicalDeviceGroup.cpp",
    "src/objects/pipeline.cpp",
    "src/objects/pipelineBatch.cpp",
    "src/objects/pipelineCache.cpp",
    "src/objects/pipelineLayout.cpp",
    "src/objects/pipelineLibrary.cpp",
    "src/objects/primaryCommandBuffer.cpp",
    "src/objects/privateDataSlot.cpp",
    "src/objects/queryPool.cpp",
    "src/objects/queue.cpp",
    "src/objects/rayTracingPipeline.cpp",
    "src/objects/rayTracingPipelineBatch.cpp",
    "src/objects/renderPass.cpp",
    "src/objects/sampler.cpp",
    "src/objects/samplerYcbcrConversion.cpp",
    "src/objects/semaphore.cpp",
    "src/objects/shaderModule.cpp",
    "src/objects/srcTransferBuffer.cpp",
    "src/objects/storageBuffer.cpp",
    "src/objects/storageTexelBuffer.cpp",
    "src/objects/surface.cpp",
    "src/objects/swapchain.cpp",
    "src/objects/swapchainImage.cpp",
    "src/objects/timelineSemaphore.cpp",
    "src/objects/topLevelStructure.cpp",
    "src/objects/transformFeedbackBuffer.cpp",
    "src/objects/uniformTexelBuffer.cpp",
    "src/objects/validationCache.cpp",
    "src/objects/variableCountDescriptorSet.cpp",
    "src/objects/vertexBuffer.cpp",
    "src/platform/androidHardwareBuffer.cpp",
    "src/platform/androidSurface.cpp",
    "src/platform/d3dExternalSemaphore.cpp",
    "src/platform/directFbSurface.cpp",
    "src/platform/externalFence.cpp",
    "src/platform/externalSemaphore.cpp",
    "src/platform/fuchsiaSurface.cpp",
    "src/platform/iosSurface.cpp",
    "src/platform/macosSurface.cpp",
    "src/platform/metalSurface.cpp",
    "src/platform/qnxSurface.cpp",
    "src/platform/viSurface.cpp",
    "src/platform/waylandSurface.cpp",
    "src/platform/win32ExternalSemaphore.cpp",
    "src/platform/win32Surface.cpp",
    "src/platform/xcbSurface.cpp",
    "src/platform/xlibSurface.cpp",
    "src/raytracing/accelerationStructureGeometry.cpp",
    "src/renderpass/subpass.cpp",
    "src/shaders/pipelineShaderStage.cpp",
    "src/shaders/shaderBindingTable.cpp",
    "src/shaders/shaderGroup.cpp",
    "src/shaders/shaderReflection.cpp",
    "src/shaders/specialization.cpp",
    "src/states/colorBlendStateAdvanced.cpp",
    "src/states/formattedOutput.cpp",
    "src/states/multiColorBlendState.cpp",
    "src/states/multisampleState.cpp",
    "src/states/multiViewportState.cpp",
    "src/states/rasterizationState.cpp",
    "src/states/vertexInputState.cpp",
    "src/states/vertexInputStructure.cpp",
    "src/states/viewportState.cpp",
    "src/third-party/SPIRV-Reflect/spirv_reflect.c"
  }

  links {
    "%VULKAN_SDK%/Lib/vulkan-1.lib"
  }

  prebuildcommands {
    "mkdir -p src/auxiliary/spirv/output/blitf",
    "mkdir -p src/auxiliary/spirv/output/blitv",
    "mkdir -p src/auxiliary/spirv/output/blitv_nv",
    "mkdir -p src/auxiliary/spirv/output/fontf",
    "mkdir -p src/auxiliary/spirv/output/immv",
    "mkdir -p src/auxiliary/spirv/output/immf",
    glslc .. " -V --vn fsBlit " .. GLSL_DIR .. "/blit.frag -o " .. SPIRV_DIR .. "/blitf/fsBlit.h",
    glslc .. " -V --vn vsBlit " .. GLSL_DIR .. "/blit.vert -o " .. SPIRV_DIR .. "/blitv/vsBlit.h",
    glslc .. " -V -DNV --vn vsBlitNV " .. GLSL_DIR .. "/blit.vert -o " .. SPIRV_DIR .. "/blitv_nv/vsBlitNV.h",
    glslc .. " -V --vn fsFont " .. GLSL_DIR .. "/font.frag -o " .. SPIRV_DIR .. "/fontf/fsFont.h",
    glslc .. " -V --vn vsImm " .. GLSL_DIR .. "/imm.vert -o " .. SPIRV_DIR .. "/immv/vsImm.h",
    glslc .. " -V --vn fsImm " .. GLSL_DIR .. "/imm.frag -o " .. SPIRV_DIR .. "/immf/fsImm.h"
  }

filter "system:windows"
  defines { "VK_USE_PLATFORM_WIN32_KHR" }      

filter {"configurations:Debug"}
  buildoptions {"/MTd"}
    
filter {"configurations:Release"}
  buildoptions {"/MT"}


